# Generated by Django 6.0.6 on 2026-06-26 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique device identifier",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable device name",
                        max_length=255,
                        verbose_name="Device Name",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        help_text="Device model (e.g., ESP32, Raspberry Pi)",
                        max_length=255,
                        verbose_name="Model",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        help_text="Device username for authentication",
                        max_length=150,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        help_text="Device password (stored in plain text for device communication)",
                        max_length=128,
                        verbose_name="Password",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the device is active and allowed to connect",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ["-created_at"],
            },
        ),
    ]
