# Generated by Django 6.0.6 on 2026-06-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="topics",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of topics the device can publish/subscribe to",
                verbose_name="Topics",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="password",
            field=models.CharField(
                help_text="Device password (hashed)",
                max_length=128,
                verbose_name="Password",
            ),
        ),
    ]
